### ISSUE TITLE
user.index name

### ISSUE THREAD

**Issue by swdriessen** [chris-velox/aurora-elements#1]
Just a friendly suggestion, i recommend you change the name of the index from `user.index` to something else. The user folder is somewhat special and specific for the user. The builder also excludes or explicitly includes it from certain checks which may result in unexpected behavior. It currently doesn't block a `user.index` from being added but there is a good change it will in the future.

**Comment by chris-velox** [comment]
Thanks, Bas, I'll take a look at that. I use that for my testing files and internal stuff and have shared the link only with my D&D group. Maybe I'll create a private.index or something like that.

**Comment by swdriessen** [comment]
Yeah, that's exactly the way it should be used.

👍
